### ISSUE TITLE
My Spec Complaint Fork

### ISSUE THREAD

**Issue by BenjaminHinchliff** [shnewto/ashpaper#44]
I thought that this was a really cool project, but was sad to see that it still didn't implement rhyming or alliteration support. It looks like something was in the works, but it seems to be from 2019, so I thought I'd try my hand at it. I would appreciate your thoughts on my attempt and would like to know if you'd consider a pull request.

The reason I'm raising an issue rather than a pull request is that my fork is a substantial deviation from the initial project - rather than using a Pest parser, it replaces that with a more flexible, custom solution. However, I don't know if that's what you want in your project, so it's really up to you.

The parser itself is mainly modeled after the parsing logic in the original Python interpreter, with a few enhancements:
- all syllable counting is handled at parse time and passed to the executor
- each instruction passes the register to which it's applicable (eliminating internal state beyond the stack and registers)
- rhyming and alliteration are both determined at parse time rather than during execution

The syllable counting is done with a custom version of the `cmudict` crate, called `cmudict-fast` that I put together. It optimizes lookup time by loading the entire dictionary into a hashmap in volitile memory, obviously at the cost of startup time. As a backup, it uses the exact same method as the original crate & Python interpreter of counting vowel clusters. Since the original Ashpaper interpreter also used the cmu dictionary, programs written for it should also work with this one. It doesn't, however, run identically to your original crate in all cases (for example, you'll notice `lovely-poem.eso` is missing an `a` on line 17).

To make sure the interpreter can be distributed as a single executable, the dictionary is embedded into it, which increases executable size by about 3.5 MB

The executor is mostly the same, just modified to use the enumerations from the new parser and with added instruction handling for the new features.

I additionally added an argument to the CLI to tell a user how many syllables a string contains to make determining the actual syllable count easier for the user.

I'm still in the process of writing comprehensive tests and documenting the code, but the library itself should all be working.

If I remember any other major changes I'll update this appropriately.

In terms of far-off plans, I plan to make an LLVM backend at some point.

Also, thank you - your interpreter was how I originally found the AshPaper language, and it's been a lot of fun to get this working.

Please let me know your thoughts, and if you have any questions, comments, and concerns.

**Comment by BenjaminHinchliff** [comment]
oh, right, repository link
[https://github.com/BenjaminHinchliff/ashpaper](https://github.com/BenjaminHinchliff/ashpaper)

**Comment by shnewto** [comment]
Hi @BenjaminHinchliff 👋 
Wow, lots to take in, sounds like some fantastic stuff you've put together ❤️ I'd like to poke around your fork a bit to see how I feel about the substantial deviations before making a decision about a PR though. I'm really curious what it was about Pest that you felt wasn't flexible enough, was there a specific scenario/s it wasn't able to handle?

I'm happy to hear about other people discovering AshPaper and glad about being one of the reasons for that 😄 
Thanks for raising this issue!

**Comment by BenjaminHinchliff** [comment]
Hi @shnewto - thanks for taking an interest in my fork!
The primary reason for leaving pest was that it's unable to implement the rhyming rules in-grammar. Ideally, I'd like it to have a feature allowing for rules to be defined by arbitrary code (to do dictionary lookups in cmudict), but it doesn't seem that's possible (AFAIK). In hindsight, I think I probably should've just written a postprocessing pass that found rhyming instructions and replaced them, but, well, hindsight is 20/20.

I think there is still a good argument for not using a parser generator since it allows everything to be done in one stage, cleanly separates parsing and executing logic, along with being more approachable to new users (since it's just regular rust). Not as strong of one as I thought, though - It turns out that Alliteration might be possible to implement with [pest's stack](https://pest.rs/book/grammars/syntax.html#the-stack-wip) (assuming it's api stable).

**Comment by shnewto** [comment]
👋  Heyo @BenjaminHinchliff, I took a look at your fork and it's great! I do think AshPaper Plus qualifies properly as a distinct project/package/crate though so I'll vote for it continuing under your user however you'd like to handle that, rather than incorporating it here. Definitely thanks for pointing me at it and giving some context to the direction you took! If you ever do work out that LLVM backend ping me, I'd love to check it out :) Also if you haven't pinged William Hicks, I imagine they'd be glad to see someone else finding some joy in the language.

**Comment by BenjaminHinchliff** [comment]
I'm glad to see that you're interested in the native backend - it's in the works (although it'll take me a bit to get everything working due to my inexperience with cranelift). I'll close the issue now since this has been resolved.
